Description: AWS CloudFormation template to create a beanstalk environment for an SFTP Proxy server

Parameters:
  ApplicationStackName:
    Type: String
    Description: The name of the Beanstalk application Cloudformation stack
    Default: sftpproxyapp
  AppHealthcheckUrl:
    Type: String
    Description: The AWS EB health check path
    Default: '/'
  EbHealthReportingSystem:
    Type: String
    Default: basic
    AllowedValues:
      - basic
      - enhanced
    ConstraintDescription: must be either basic or enhanced
  EC2InstanceType:
    Type: String
    Description: Instance type to use for Elastic Beanstalk Instances
    Default: t3.micro
  EC2KeyName:
    Description: An existing EC2 keypair to allow secure access to instances
    Type: String
  ArtifactKey:
    Description: The S3 file that contains the deployed code
    Type: String
  AcmCertArn:
    Description: The ARN of the ACM certificate used for the endpoint
    Type: String

Resources:

  BeanstalkApplicationVersion:
    Type: 'AWS::ElasticBeanstalk::ApplicationVersion'
    Properties:
      ApplicationName:
        Fn::ImportValue:
          !Sub 'us-east-1-${ApplicationStackName}-BeanstalkAppName'
      Description: Artifact for SFPT Proxy instance
      SourceBundle:
        S3Bucket:
          Fn::ImportValue:
            !Sub 'us-east-1-${ApplicationStackName}-AppDeployBucketName'
        S3Key: !Ref ArtifactKey

  BeanstalkConfigTemplate:
    Type: 'AWS::ElasticBeanstalk::ConfigurationTemplate'
    Properties:
      ApplicationName:
        Fn::ImportValue:
          !Sub 'us-east-1-${ApplicationStackName}-BeanstalkAppName'
      Description: Environment for SFTP Proxy server Beanstalk stack
      SolutionStackName: '64bit Amazon Linux 2 v4.2.11 running Tomcat 8.5 Corretto 8'
      OptionSettings:
        # EB environment options
        - Namespace: 'aws:ec2:vpc'
          OptionName: VPCId
          Value: !ImportValue us-east-1-synapse-ops-vpc-v2-VPCId
        - Namespace: 'aws:ec2:vpc'
          OptionName: ELBScheme
          Value: 'public'
        - Namespace: 'aws:ec2:vpc'
          OptionName: AssociatePublicIpAddress
          Value: 'false'
        - Namespace: 'aws:ec2:vpc'
          OptionName: Subnets
          Value: !Join
            - ','
            - - !ImportValue us-east-1-synapse-ops-vpc-v2-PrivateSubnet
              - !ImportValue us-east-1-synapse-ops-vpc-v2-PrivateSubnet1
        - Namespace: 'aws:ec2:vpc'
          OptionName: ELBSubnets
          Value: !Join
            - ','
            - - !ImportValue us-east-1-synapse-ops-vpc-v2-PublicSubnet
              - !ImportValue us-east-1-synapse-ops-vpc-v2-PublicSubnet1
        - Namespace: 'aws:autoscaling:asg'
          OptionName: MaxSize
          Value: 4
        - Namespace: 'aws:autoscaling:asg'
          OptionName: MinSize
          Value: 2
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: EC2KeyName
          Value: !Ref EC2KeyName
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: IamInstanceProfile
          Value: aws-elasticbeanstalk-ec2-role
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: InstanceType
          Value: !Ref EC2InstanceType
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: SecurityGroups
          Value: !ImportValue us-east-1-synapse-ops-vpc-v2-VpnSecurityGroup
        - Namespace: 'aws:autoscaling:updatepolicy:rollingupdate'
          OptionName: RollingUpdateEnabled
          Value: 'true'
        - Namespace: 'aws:elasticbeanstalk:environment:process:default'
          OptionName: HealthCheckInterval
          Value: 30
        - Namespace: 'aws:elasticbeanstalk:environment:process:default'
          OptionName: HealthCheckPath
          Value: !Ref AppHealthcheckUrl
        - Namespace: 'aws:elasticbeanstalk:environment:process:default'
          OptionName: HealthCheckTimeout
          Value: 5
        - Namespace: 'aws:elasticbeanstalk:environment:process:default'
          OptionName: HealthyThresholdCount
          Value: 2
        - Namespace: 'aws:elasticbeanstalk:environment:process:default'
          OptionName: UnhealthyThresholdCount
          Value: 5
        - Namespace: 'aws:elasticbeanstalk:environment:process:default'
          OptionName: Protocol
          Value: 'HTTPS'
        - Namespace: 'aws:elasticbeanstalk:environment:process:default'
          OptionName: Port
          Value: 443
        - Namespace: 'aws:elasticbeanstalk:environment'
          OptionName: ServiceRole
          Value:
            Fn::ImportValue:
              !Sub 'us-east-1-${ApplicationStackName}-BeanstalkServiceRole'
        - Namespace: 'aws:elasticbeanstalk:environment'
          OptionName: LoadBalancerType
          Value: 'application'
        - Namespace: aws:elasticbeanstalk:environment:proxy
          OptionName: ProxyServer
          Value: apache
        - Namespace: 'aws:elasticbeanstalk:cloudwatch:logs'
          OptionName: StreamLogs
          Value: 'true'
        - Namespace: 'aws:elasticbeanstalk:cloudwatch:logs'
          OptionName: DeleteOnTerminate
          Value: 'true'
        - Namespace: 'aws:elasticbeanstalk:cloudwatch:logs'
          OptionName: RetentionInDays
          Value: '90'
        - Namespace: 'aws:elasticbeanstalk:command'
          OptionName: DeploymentPolicy
          Value: AllAtOnce
        - Namespace: 'aws:elbv2:loadbalancer'
          OptionName: AccessLogsS3Bucket
          Value:
            Fn::ImportValue:
              !Sub 'us-east-1-${ApplicationStackName}-LoadBalancerAccessLogsBucketName'
        - Namespace: 'aws:elbv2:loadbalancer'
          OptionName: AccessLogsS3Enabled
          Value: true
        - Namespace: 'aws:elbv2:listener:default'
          OptionName: ListenerEnabled
          Value: false
        - Namespace: 'aws:elbv2:listener:443'
          OptionName: Protocol
          Value: 'HTTPS'
        - Namespace: 'aws:elbv2:listener:443'
          OptionName: SSLCertificateArns
          Value: !Ref AcmCertArn
        - Namespace: 'aws:elasticbeanstalk:healthreporting:system'
          OptionName: SystemType
          Value: !Ref EbHealthReportingSystem
        - Namespace: 'aws:elasticbeanstalk:hostmanager'
          OptionName: LogPublicationControl
          Value: 'true'

  BeanstalkEnvironment:
    Type: 'AWS::ElasticBeanstalk::Environment'
    Properties:
      ApplicationName:
        Fn::ImportValue:
          !Sub 'us-east-1-${ApplicationStackName}-BeanstalkAppName'
      TemplateName: !Ref BeanstalkConfigTemplate
      EnvironmentName: !Join
        - '-'
        - - !Ref 'AWS::StackName'
      Tier:
        Name: WebServer
        Type: Standard
      VersionLabel: !Ref BeanstalkApplicationVersion

Outputs:
  BeanstalkEnvironmentName:
    Value: !Ref BeanstalkEnvironment
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BeanstalkEnvironmentName'